<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="BabluKumarPrasa" name="com.create4.execution.Home_Page_Details_TS_02" tests="7" failures="0" timestamp="08 Apr 2018 04:53:56 GMT" time="0.000" errors="1">
  <testcase name="CRe4_06" time="0.000" classname="com.create4.execution.Home_Page_Details_TS_02">
    <skipped/>
  </testcase> <!-- CRe4_06 -->
  <testcase name="beforeMethod" time="0.000" classname="com.create4.execution.Home_Page_Details_TS_02">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.interactions.Actions.<init>(Actions.java:44)
	at com.global.methods.GlobalMethods.<init>(GlobalMethods.java:44)
	at com.create4.execution.Home_Page_Details_TS_02.beforeMethod(Home_Page_Details_TS_02.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="CRe4_10" time="0.000" classname="com.create4.execution.Home_Page_Details_TS_02">
    <skipped/>
  </testcase> <!-- CRe4_10 -->
  <testcase name="CRe4_09" time="0.000" classname="com.create4.execution.Home_Page_Details_TS_02">
    <skipped/>
  </testcase> <!-- CRe4_09 -->
  <testcase name="CRe4_05" time="0.000" classname="com.create4.execution.Home_Page_Details_TS_02">
    <skipped/>
  </testcase> <!-- CRe4_05 -->
  <testcase name="CRe4_01_02_03_08_10_11" time="0.000" classname="com.create4.execution.Home_Page_Details_TS_02">
    <skipped/>
  </testcase> <!-- CRe4_01_02_03_08_10_11 -->
  <testcase name="CRe4_04" time="0.000" classname="com.create4.execution.Home_Page_Details_TS_02">
    <skipped/>
  </testcase> <!-- CRe4_04 -->
</testsuite> <!-- com.create4.execution.Home_Page_Details_TS_02 -->
